# Generated by Django 4.2.4 on 2024-06-24 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('testing_time', models.TimeField(default=datetime.timedelta(seconds=3600), verbose_name='testing time')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(verbose_name='Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='photo')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='correct answer')),
                ('incorrect_answer_1', models.CharField(max_length=200, verbose_name='incorrect answer 1')),
                ('incorrect_answer_2', models.CharField(max_length=200, verbose_name='incorrect answer 2')),
                ('incorrect_answer_3', models.CharField(max_length=200, verbose_name='incorrect answer 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='questions.tour')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
    ]
