# Generated by Django 4.2.4 on 2024-05-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
        ("users", "0002_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationdata",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AlterField(
            model_name="registrationdata",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reg_area",
                to="location.area",
            ),
        ),
        migrations.AlterField(
            model_name="registrationdata",
            name="job_position",
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Job/Study place and Position",
            ),
        ),
        migrations.AlterField(
            model_name="registrationdata",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reg_region",
                to="location.region",
            ),
        ),
        migrations.AlterField(
            model_name="registrationdata",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reg_village",
                to="location.village",
            ),
        ),
    ]
