# Generated by Django 4.2.4 on 2024-06-24 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_area_region_alter_village_area'),
        ('users', '0004_telegramuser_is_white_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos  ',
            },
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_area', to='location.area'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_region', to='location.region'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_village', to='location.village'),
        ),
    ]
