# Generated by Django 4.2.4 on 2024-06-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='location.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='village',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='location.area', verbose_name='Area'),
        ),
    ]
